import { auth } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { redirect } from "next/navigation";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Calendar, Sparkles, AlertTriangle, FileEdit, TrendingUp, ChevronRight, Mail } from "lucide-react";
import { GenerateNowButton } from "./generate-now-button";

export const dynamic = "force-dynamic";

export default async function BriefingsPage() {
  const session = await auth();
  if (!session?.user?.id) redirect("/login");

  const briefings = await prisma.dailyBriefing.findMany({
    where: { userId: session.user.id },
    orderBy: { forDate: "desc" },
    take: 14,
  });

  const [today, ...prior] = briefings as any[];

  // Week-over-week metrics — sum of last 7 briefings vs prior 7.
  const last7 = briefings.slice(0, 7) as any[];
  const totalThreads = last7.reduce((a, b) => a + (b.threadsTriaged ?? 0), 0);
  const totalDrafts = last7.reduce((a, b) => a + (b.pendingDrafts ?? 0), 0);
  const totalEsc = last7.reduce((a, b) => a + (b.openEscalations ?? 0), 0);
  const avgReplyRate =
    last7.length > 0 ? last7.reduce((a, b) => a + (b.aiReplyRate ?? 0), 0) / last7.length : 0;

  return (
    <div className="h-full overflow-y-auto bg-background">
      <div className="mx-auto max-w-a3-content p-4 md:p-8">
        {/* Header */}
        <header className="mb-6 flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <div className="a3-label mb-1 text-a3-fog">7am · Daily for the GM</div>
            <h2 className="flex items-center gap-3 text-[22px] font-extrabold tracking-tight text-foreground md:text-[28px]">
              <Calendar className="h-7 w-7 text-primary" />
              Executive Briefings
            </h2>
            <p className="mt-1 text-[12px] text-muted-foreground">
              A personalized morning brief generated by the digest agent on your live inbox state.
            </p>
          </div>
          <GenerateNowButton />
        </header>

        {briefings.length === 0 ? (
          <Card>
            <CardContent className="flex flex-col items-center gap-3 p-12 text-center">
              <div className="grid h-12 w-12 place-items-center rounded-full bg-primary/10 text-primary">
                <Calendar className="h-6 w-6" />
              </div>
              <div className="text-[15px] font-bold text-foreground">No briefings yet.</div>
              <p className="max-w-sm text-[13px] text-muted-foreground">
                They generate automatically at 7am. Want to see one now? Click <em>Generate Now</em>.
              </p>
            </CardContent>
          </Card>
        ) : (
          <>
            {/* Week-over-week metrics row */}
            <div className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4">
              <Metric icon={Mail} label="Threads this week" value={totalThreads} />
              <Metric icon={FileEdit} label="Drafts shipped" value={totalDrafts} />
              <Metric icon={AlertTriangle} label="Escalations" value={totalEsc} tone="text-red-600 dark:text-red-400" />
              <Metric
                icon={TrendingUp}
                label="AI reply rate"
                value={`${Math.round(avgReplyRate * 100)}%`}
                tone="text-emerald-600 dark:text-emerald-400"
              />
            </div>

            {/* Today — hero card */}
            {today && <HeroBriefing brief={today} />}

            {/* Prior days */}
            {prior.length > 0 && (
              <div className="mt-8 space-y-4">
                <div className="a3-label text-a3-fog">Earlier this week</div>
                {prior.map((b: any) => (
                  <PriorBriefing key={b.id} brief={b} />
                ))}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}

function Metric({
  icon: Icon,
  label,
  value,
  tone,
}: {
  icon: typeof Mail;
  label: string;
  value: string | number;
  tone?: string;
}) {
  return (
    <Card>
      <CardContent className="p-4">
        <div className="flex items-center gap-2">
          <Icon className={`h-3.5 w-3.5 ${tone ?? "text-primary"}`} />
          <span className="a3-label text-a3-fog">{label}</span>
        </div>
        <div className={`mt-1 text-[24px] font-extrabold tracking-tight md:text-[28px] ${tone ?? "text-foreground"}`}>
          {value}
        </div>
      </CardContent>
    </Card>
  );
}

function HeroBriefing({ brief }: { brief: any }) {
  const date: Date = brief.forDate instanceof Date ? brief.forDate : new Date(brief.forDate);
  const topThreads = parseTopThreads(brief.topThreads);
  return (
    <Card className="border-primary/30 bg-primary/[0.03] shadow-emerald">
      <CardContent className="space-y-4 p-6 md:p-8">
        <div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between">
          <div>
            <Badge variant="status" className="border-primary/60 bg-primary/10 text-primary">
              Today · {date.toLocaleDateString(undefined, { weekday: "long", month: "short", day: "numeric" })}
            </Badge>
            <h3 className="mt-2 text-[20px] font-extrabold tracking-tight text-foreground md:text-[24px]">
              Your morning brief
            </h3>
          </div>
          <div className="flex flex-wrap gap-2">
            {(brief.openEscalations ?? 0) > 0 && (
              <Badge variant="critical">
                {brief.openEscalations} escalation{brief.openEscalations === 1 ? "" : "s"}
              </Badge>
            )}
            {(brief.newLeads ?? 0) > 0 && (
              <Badge variant="status">
                {brief.newLeads} new lead{brief.newLeads === 1 ? "" : "s"}
              </Badge>
            )}
            {(brief.pendingDrafts ?? 0) > 0 && (
              <Badge variant="secondary">
                {brief.pendingDrafts} draft{brief.pendingDrafts === 1 ? "" : "s"}
              </Badge>
            )}
          </div>
        </div>

        <p className="text-[14px] leading-relaxed text-foreground md:text-[15px]">{brief.summary}</p>

        {topThreads.length > 0 && (
          <div className="space-y-2 rounded-lg border border-border bg-card p-4 md:p-5">
            <div className="a3-label text-a3-fog">Top of your pile</div>
            <ul className="space-y-1.5">
              {topThreads.map((t, i) => (
                <li key={t.threadId ?? i}>
                  <Link
                    href={`/inbox/${t.threadId}`}
                    className="group flex items-start gap-3 rounded-md px-2 py-2 transition-colors hover:bg-secondary"
                  >
                    <span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-sm bg-primary/10 font-mono text-[11px] font-bold text-primary">
                      {i + 1}
                    </span>
                    <div className="flex-1">
                      <div className="text-[13px] font-semibold text-foreground group-hover:text-primary md:text-[14px]">
                        {t.subject ?? t.reason}
                      </div>
                      {t.subject && t.reason ? (
                        <div className="mt-0.5 text-[11px] text-muted-foreground md:text-[12px]">{t.reason}</div>
                      ) : null}
                    </div>
                    <ChevronRight className="mt-1 h-3.5 w-3.5 shrink-0 text-muted-foreground group-hover:text-primary" />
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        )}

        <footer className="flex items-center justify-between border-t border-border pt-3 text-[10px] uppercase tracking-wider text-a3-fog md:text-[11px]">
          <span className="inline-flex items-center gap-1">
            <Sparkles className="h-3 w-3 text-primary" />
            Generated by {brief.modelUsed ?? "AI"} · 7:00 AM
          </span>
          <Link href="/inbox" className="font-medium text-primary hover:underline">
            Open inbox →
          </Link>
        </footer>
      </CardContent>
    </Card>
  );
}

function PriorBriefing({ brief }: { brief: any }) {
  const date: Date = brief.forDate instanceof Date ? brief.forDate : new Date(brief.forDate);
  const topThreads = parseTopThreads(brief.topThreads);
  return (
    <Card>
      <CardContent className="space-y-3 p-5">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <div className="text-[13px] font-bold text-foreground md:text-[14px]">
            {date.toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric" })}
          </div>
          <div className="flex flex-wrap gap-2">
            {(brief.openEscalations ?? 0) > 0 && (
              <Badge variant="critical" className="text-[10px]">
                {brief.openEscalations} esc
              </Badge>
            )}
            {(brief.pendingDrafts ?? 0) > 0 && (
              <Badge variant="secondary" className="text-[10px]">
                {brief.pendingDrafts} drafts
              </Badge>
            )}
          </div>
        </div>
        <p className="text-[13px] leading-relaxed text-muted-foreground">{brief.summary}</p>
        {topThreads.length > 0 && (
          <div className="flex flex-wrap gap-1.5 pt-1">
            {topThreads.slice(0, 3).map((t) => (
              <Link
                key={t.threadId}
                href={`/inbox/${t.threadId}`}
                className="inline-flex max-w-full items-center gap-1 truncate rounded-sm border border-border bg-secondary px-2 py-0.5 text-[10px] font-medium text-muted-foreground hover:border-primary/40 hover:text-foreground"
              >
                <Mail className="h-2.5 w-2.5" />
                <span className="truncate">{(t.subject ?? t.reason ?? "").slice(0, 60)}</span>
              </Link>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function parseTopThreads(raw: unknown): Array<{ threadId?: string; subject?: string; reason?: string; priority?: string }> {
  if (Array.isArray(raw)) return raw as any[];
  if (typeof raw === "string" && raw) {
    try {
      const parsed = JSON.parse(raw);
      return Array.isArray(parsed) ? parsed : [];
    } catch {
      return [];
    }
  }
  return [];
}
